### ISSUE TITLE
Test::Data::Scalar::dualvar_ok documented (and exported), but  commented out, code for dualvar_ok leaks into POD

### ISSUE THREAD

**Issue by jwrightecs** [briandfoy/test-data#12]
`Test::Data::Scalar::dualvar_ok`  is still exported and documented, despite being commented out (the documentation also leaks the code for the function.

`dualvar_ok` should be able to use `Scalar::Util::isdual` function to determine the dual nature of a scalar, though it might be best to document the caveats from `Scalar::Util::isdual` POD

>     Note that a scalar can be made to have both string and numeric content
>     through standard operations:

a working `dualvar_ok`

```
=item dualvar_ok( SCALAR )

Ok if the scalar is a dualvar.

=cut

sub dualvar_ok ($;$)
        {
        my $ok   = Scalar::Util::isdual( $_[0] );
        my $name = $_[1] || 'Scalar is a dualvar';

        $Test->ok( $ok, $name );

        $Test->diag("Expected a dualvar, didn't get it\n")
                unless $ok;
        }

```

**Comment by briandfoy** [comment]
Released as 1.246.

Thanks,
